# Generated by Django 4.0.5 on 2022-07-06 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Earnings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_number', models.IntegerField(verbose_name='納品no')),
                ('line_number', models.IntegerField(verbose_name='行no')),
                ('sales_date', models.DateField(blank=True, null=True, verbose_name='売上日')),
                ('customer_code', models.CharField(max_length=6, verbose_name='得意先コード')),
                ('customer_name', models.CharField(max_length=30, verbose_name='得意先名')),
                ('delivery_code', models.CharField(max_length=10, verbose_name='納品先コード')),
                ('delivery_name', models.CharField(max_length=50, verbose_name='納品先名')),
                ('post_code', models.CharField(blank=True, max_length=8, null=True, verbose_name='郵便番号')),
                ('address1', models.CharField(blank=True, max_length=50, null=True, verbose_name='住所1')),
                ('address2', models.CharField(blank=True, max_length=50, null=True, verbose_name='住所2')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='ＴＥＬ')),
                ('overview', models.CharField(blank=True, max_length=30, null=True, verbose_name='摘要')),
                ('slip_number', models.CharField(max_length=10, verbose_name='伝票番号')),
                ('order_number', models.CharField(max_length=10, verbose_name='注文番号')),
                ('total_tax_excluded_amount', models.IntegerField(blank=True, null=True, verbose_name='合計税抜金額')),
                ('total_tax_amount', models.IntegerField(blank=True, null=True, verbose_name='合計消費税')),
                ('total_tax_included', models.IntegerField(blank=True, null=True, verbose_name='合計税込金額')),
                ('transaction_classification', models.CharField(max_length=3, verbose_name='取引区分')),
                ('transaction_classification_name', models.CharField(max_length=5, verbose_name='取引区分名')),
                ('product_code', models.CharField(max_length=6, verbose_name='商品コード')),
                ('product_name', models.CharField(max_length=30, verbose_name='商品名')),
                ('warehouse_code', models.CharField(max_length=5, verbose_name='倉庫コード')),
                ('warehouse_name', models.CharField(max_length=10, verbose_name='倉庫名')),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name='総数量')),
                ('tax_excluded_amount', models.IntegerField(blank=True, null=True, verbose_name='税抜金額')),
                ('tax_amount', models.IntegerField(blank=True, null=True, verbose_name='消費税額')),
                ('tax_included', models.IntegerField(blank=True, null=True, verbose_name='税込金額')),
                ('line_overview', models.CharField(max_length=30, verbose_name='行摘要')),
                ('input_date', models.DateTimeField(verbose_name='入力日')),
                ('correction_date', models.DateTimeField(blank=True, null=True, verbose_name='訂正日')),
                ('delete_date', models.DateTimeField(blank=True, null=True, verbose_name='削除日')),
                ('billing_code', models.CharField(max_length=6, verbose_name='請求先コード')),
                ('billing_name', models.CharField(max_length=10, verbose_name='請求先名')),
                ('customer_category_3', models.CharField(blank=True, max_length=3, null=True, verbose_name='得意先区分3')),
                ('customer_category_name_3', models.CharField(blank=True, max_length=10, null=True, verbose_name='得意先区分名3')),
                ('shipping_code', models.CharField(max_length=3, verbose_name='運送コード')),
                ('consumption_tax_classification', models.CharField(blank=True, max_length=3, null=True, verbose_name='消費税区分')),
                ('time_specification_code', models.CharField(blank=True, max_length=3, null=True, verbose_name='時間指定コード')),
                ('time_designation_division_name', models.CharField(blank=True, max_length=15, null=True, verbose_name='時間指定区分名')),
                ('specify_time', models.CharField(blank=True, max_length=10, null=True, verbose_name='時間指定')),
                ('shipping_description_1', models.CharField(blank=True, max_length=20, null=True, verbose_name='出荷摘要１')),
                ('shipping_description_2', models.CharField(blank=True, max_length=20, null=True, verbose_name='出荷摘要２')),
                ('invoice_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='送り状№')),
            ],
            options={
                'verbose_name': '楽商売上明細データ',
                'verbose_name_plural': '楽商売上明細データ',
            },
        ),
    ]
