# Generated by Django 4.0.5 on 2022-07-21 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappB', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earnings',
            name='order_number',
            field=models.CharField(max_length=10, unique=True, verbose_name='注文番号'),
        ),
    ]
