# Generated by Django 4.0.5 on 2022-06-30 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('code', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='注文番号')),
                ('date', models.DateField(blank=True, null=True, verbose_name='日付')),
                ('name', models.CharField(max_length=30, verbose_name='注文者')),
                ('amount', models.IntegerField(verbose_name='注文金額')),
                ('postage', models.IntegerField(verbose_name='送料')),
                ('delivery_fee', models.IntegerField(verbose_name='代金引換手数料')),
                ('point', models.IntegerField(verbose_name='利用ポイント')),
                ('tax', models.IntegerField(verbose_name='消費税')),
                ('method', models.CharField(max_length=30, verbose_name='決済方法')),
                ('slip', models.CharField(max_length=30, verbose_name='伝票番号')),
                ('coupon', models.CharField(max_length=30, verbose_name='クーポン割引額')),
                ('correction_amount', models.IntegerField(verbose_name='修正額')),
                ('group', models.CharField(max_length=30, verbose_name='グループ名')),
            ],
            options={
                'verbose_name': '注文情報(ﾋﾞｱﾊｳｽｵﾝﾗｲﾝｼｮｯﾌﾟ)',
                'verbose_name_plural': '注文情報(ﾋﾞｱﾊｳｽｵﾝﾗｲﾝｼｮｯﾌﾟ)',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='入金者')),
            ],
            options={
                'verbose_name': '入金項目',
                'verbose_name_plural': '入金項目',
            },
        ),
        migrations.CreateModel(
            name='Earnings',
            fields=[
                ('delivery_number', models.IntegerField(verbose_name='納品no')),
                ('line_number', models.IntegerField(verbose_name='行no')),
                ('sales_date', models.DateField(blank=True, null=True, verbose_name='売上日')),
                ('customer_code', models.CharField(max_length=6, verbose_name='得意先コード')),
                ('customer_name', models.CharField(max_length=30, verbose_name='得意先名')),
                ('delivery_code', models.CharField(max_length=10, verbose_name='納品先コード')),
                ('delivery_name', models.CharField(max_length=50, verbose_name='納品先名')),
                ('post_code', models.CharField(blank=True, max_length=8, null=True, verbose_name='郵便番号')),
                ('address1', models.CharField(blank=True, max_length=50, null=True, verbose_name='住所1')),
                ('address2', models.CharField(blank=True, max_length=50, null=True, verbose_name='住所2')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='ＴＥＬ')),
                ('overview', models.CharField(blank=True, max_length=30, null=True, verbose_name='摘要')),
                ('slip_number', models.CharField(max_length=10, verbose_name='伝票番号')),
                ('order_number', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='number', serialize=False, to='ec_site.order', verbose_name='注文番号')),
                ('total_tax_excluded_amount', models.IntegerField(blank=True, null=True, verbose_name='合計税抜金額')),
                ('total_tax_amount', models.IntegerField(blank=True, null=True, verbose_name='合計消費税')),
                ('total_tax_included', models.IntegerField(blank=True, null=True, verbose_name='合計税込金額')),
                ('transaction_classification', models.CharField(max_length=3, verbose_name='取引区分')),
                ('transaction_classification_name', models.CharField(max_length=5, verbose_name='取引区分名')),
                ('product_code', models.CharField(max_length=6, verbose_name='商品コード')),
                ('product_name', models.CharField(max_length=30, verbose_name='商品名')),
                ('warehouse_code', models.CharField(max_length=5, verbose_name='倉庫コード')),
                ('warehouse_name', models.CharField(max_length=10, verbose_name='倉庫名')),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name='総数量')),
                ('tax_excluded_amount', models.IntegerField(blank=True, null=True, verbose_name='税抜金額')),
                ('tax_amount', models.IntegerField(blank=True, null=True, verbose_name='消費税額')),
                ('tax_included', models.IntegerField(blank=True, null=True, verbose_name='税込金額')),
                ('line_overview', models.CharField(max_length=30, verbose_name='行摘要')),
                ('input_date', models.DateTimeField(verbose_name='入力日')),
                ('correction_date', models.DateTimeField(blank=True, null=True, verbose_name='訂正日')),
                ('delete_date', models.DateTimeField(blank=True, null=True, verbose_name='削除日')),
                ('billing_code', models.CharField(max_length=6, verbose_name='請求先コード')),
                ('billing_name', models.CharField(max_length=10, verbose_name='請求先名')),
                ('customer_category_3', models.CharField(blank=True, max_length=3, null=True, verbose_name='得意先区分3')),
                ('customer_category_name_3', models.CharField(blank=True, max_length=10, null=True, verbose_name='得意先区分名3')),
                ('shipping_code', models.CharField(max_length=3, verbose_name='運送コード')),
                ('consumption_tax_classification', models.CharField(blank=True, max_length=3, null=True, verbose_name='消費税区分')),
                ('time_specification_code', models.CharField(blank=True, max_length=3, null=True, verbose_name='時間指定コード')),
                ('time_designation_division_name', models.CharField(blank=True, max_length=15, null=True, verbose_name='時間指定区分名')),
                ('specify_time', models.CharField(blank=True, max_length=10, null=True, verbose_name='時間指定')),
                ('shipping_description_1', models.CharField(blank=True, max_length=20, null=True, verbose_name='出荷摘要１')),
                ('shipping_description_2', models.CharField(blank=True, max_length=20, null=True, verbose_name='出荷摘要２')),
                ('invoice_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='送り状№')),
            ],
            options={
                'verbose_name': '楽商売上明細データ',
                'verbose_name_plural': '楽商売上明細データ',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.DateField(blank=True, null=True, verbose_name='入金日')),
                ('price', models.DecimalField(blank=True, decimal_places=0, max_digits=7, null=True, verbose_name='入金金額')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('items', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='ec_site.product', verbose_name='入金項目')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='入力者')),
            ],
            options={
                'verbose_name': '口座情報',
                'verbose_name_plural': '口座情報',
            },
        ),
        migrations.CreateModel(
            name='OrderItemDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='決済者')),
                ('price', models.DecimalField(decimal_places=0, max_digits=7, verbose_name='決済金額')),
                ('payment_code', models.CharField(blank=True, max_length=3, null=True, verbose_name='決済方法')),
                ('process_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='処理区分')),
                ('state', models.CharField(max_length=10, verbose_name='決済結果')),
                ('card_type', models.CharField(max_length=10, verbose_name='ｶｰﾄﾞﾀｲﾌﾟ')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_payment', to='ec_site.orderitem', verbose_name='口座情報')),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='number', to='ec_site.earnings', verbose_name='注文番号')),
            ],
            options={
                'verbose_name': '決済情報(GMOｲﾌﾟｼﾛﾝ)',
                'verbose_name_plural': '決済情報(GMOｲﾌﾟｼﾛﾝ)',
            },
        ),
    ]
