# Generated by Django 4.0.5 on 2022-07-01 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ec_site', '0002_rename_name_order_orderer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitemdetail',
            name='card_type',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='ｶｰﾄﾞﾀｲﾌﾟ'),
        ),
        migrations.AlterField(
            model_name='orderitemdetail',
            name='key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_payment', to='ec_site.orderitem', verbose_name='口座情報'),
        ),
        migrations.AlterField(
            model_name='orderitemdetail',
            name='state',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='決済結果'),
        ),
    ]
