# Generated by Django 4.0.5 on 2022-07-21 11:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ec_site', '0003_alter_orderitemdetail_card_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitemdetail',
            name='card_type',
            field=models.CharField(default=django.utils.timezone.now, max_length=10, verbose_name='ｶｰﾄﾞﾀｲﾌﾟ'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='OrderItemDetailEcollect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tranfer_date_year', models.CharField(max_length=4, verbose_name='振込日付（年）')),
                ('tranfer_date_month', models.CharField(max_length=2, verbose_name='振込日付（月）')),
                ('tranfer_date_day', models.CharField(max_length=2, verbose_name='振込日付（日）')),
                ('shipmentday', models.CharField(blank=True, max_length=8, null=True, verbose_name='発送日')),
                ('cod_amount', models.IntegerField(blank=True, null=True, verbose_name='代引金')),
                ('cod_charge', models.IntegerField(blank=True, null=True, verbose_name='代引手数料')),
                ('cod_card_charge', models.IntegerField(blank=True, null=True, verbose_name='カード決済事務手数料')),
                ('revenue_stamp_fee', models.IntegerField(blank=True, null=True, verbose_name='収入印紙代相当額')),
                ('type', models.CharField(max_length=10, verbose_name='種類')),
                ('sales_office', models.CharField(blank=True, max_length=10, null=True, verbose_name='回収営業所')),
                ('correction_information', models.CharField(blank=True, max_length=10, null=True, verbose_name='訂正情報')),
                ('correction_transfer_date_month', models.CharField(blank=True, max_length=2, null=True, verbose_name='訂正振込日（月）')),
                ('correction_transfer_date_day', models.CharField(blank=True, max_length=2, null=True, verbose_name='訂正振込日（日）')),
                ('transfer_target_class', models.CharField(blank=True, max_length=10, null=True, verbose_name='振込対象区分')),
                ('cod_fee_payment_method', models.CharField(blank=True, max_length=10, null=True, verbose_name='代引手数料支払方法')),
                ('shipping_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ec_site.order', verbose_name='お問い合せNo.')),
            ],
            options={
                'verbose_name': '決済情報(Eコレクト)',
                'verbose_name_plural': '決済情報(Eコレクト)',
            },
        ),
    ]
