# Generated by Django 4.0.5 on 2022-07-01 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='入金者')),
            ],
            options={
                'verbose_name': '入金項目',
                'verbose_name_plural': '入金項目',
            },
        ),
    ]
