# Generated by Django 4.0.5 on 2022-07-01 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ec_site', '0003_alter_orderitemdetail_card_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myappA', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('code', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='注文番号')),
                ('date', models.DateField(blank=True, null=True, verbose_name='日付')),
                ('orderer', models.CharField(max_length=30, verbose_name='注文者')),
                ('amount', models.IntegerField(verbose_name='注文金額')),
                ('postage', models.IntegerField(verbose_name='送料')),
                ('delivery_fee', models.IntegerField(verbose_name='代金引換手数料')),
                ('point', models.IntegerField(verbose_name='利用ポイント')),
                ('tax', models.IntegerField(verbose_name='消費税')),
                ('method', models.CharField(max_length=30, verbose_name='決済方法')),
                ('slip', models.CharField(max_length=30, verbose_name='伝票番号')),
                ('coupon', models.CharField(max_length=30, verbose_name='クーポン割引額')),
                ('correction_amount', models.IntegerField(verbose_name='修正額')),
                ('group', models.CharField(max_length=30, verbose_name='グループ名')),
            ],
            options={
                'verbose_name': '注文情報(ﾋﾞｱﾊｳｽｵﾝﾗｲﾝｼｮｯﾌﾟ)',
                'verbose_name_plural': '注文情報(ﾋﾞｱﾊｳｽｵﾝﾗｲﾝｼｮｯﾌﾟ)',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.DateField(blank=True, null=True, verbose_name='入金日')),
                ('price', models.DecimalField(blank=True, decimal_places=0, max_digits=7, null=True, verbose_name='入金金額')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('items', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='myappA.product', verbose_name='入金項目')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='入力者')),
            ],
            options={
                'verbose_name': '口座情報',
                'verbose_name_plural': '口座情報',
            },
        ),
        migrations.CreateModel(
            name='OrderItemDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='決済者')),
                ('price', models.DecimalField(decimal_places=0, max_digits=7, verbose_name='決済金額')),
                ('payment_code', models.CharField(blank=True, max_length=3, null=True, verbose_name='決済方法')),
                ('process_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='処理区分')),
                ('state', models.CharField(blank=True, max_length=10, null=True, verbose_name='決済結果')),
                ('card_type', models.CharField(blank=True, max_length=10, null=True, verbose_name='ｶｰﾄﾞﾀｲﾌﾟ')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ec_site.earnings', verbose_name='注文番号')),
                ('key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_payment', to='myappA.orderitem', verbose_name='口座情報')),
            ],
            options={
                'verbose_name': '決済情報(GMOｲﾌﾟｼﾛﾝ)',
                'verbose_name_plural': '決済情報(GMOｲﾌﾟｼﾛﾝ)',
            },
        ),
    ]
