# Generated by Django 4.0.5 on 2022-07-01 19:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ec_site', '0003_alter_orderitemdetail_card_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myappA', '0002_order_orderitem_orderitemdetail'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='Order2',
        ),
        migrations.RenameModel(
            old_name='OrderItem',
            new_name='OrderItem2',
        ),
        migrations.RenameModel(
            old_name='OrderItemDetail',
            new_name='OrderItemDetail2',
        ),
        migrations.RenameModel(
            old_name='Product',
            new_name='Product2',
        ),
    ]
