# Generated by Django 4.0.5 on 2022-10-24 10:42

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myappA', '0003_rename_order_order2_rename_orderitem_orderitem2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem2',
            name='pdf_file',
            field=models.FileField(default=django.utils.timezone.now, upload_to='uploads/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='PDFファイル'),
            preserve_default=False,
        ),
    ]
