"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 3.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = '/'

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-n5ult=#l9+u!#wt%d2^llhtap3v(38$1+&18$vxkhp*0n=(vov'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'ec_site.apps.EcSiteConfig',
    'debug_toolbar', #追加
    'import_export',
    'myappA', #追加
    #'social_django',  # 追加
    'myappB', #追加
    'myappC', #追加
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', # この行を追加
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',  # 追加
#    'social_django.middleware.SocialAuthExceptionMiddleware',  # 追加
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
#                'social_django.context_processors.backends',  # 追加
#                'social_django.context_processors.login_redirect', # 追加
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

#AUTHENTICATION_BACKENDS = (
#    'social_core.backends.open_id.OpenIdAuth',  # OpenId用
#    'social_core.backends.google.GoogleOpenId',  # Google OpenId用
#    'social_core.backends.google.GoogleOAuth2',  # Google OAuth2用
#
#    'social_core.backends.github.GithubOAuth2',  # Github用
#    'social_core.backends.twitter.TwitterOAuth',  # Twitter用
#    'social_core.backends.facebook.FacebookOAuth2',  # Facebook用
#
#    'django.contrib.auth.backends.ModelBackend',  # デフォルトバックエンド、必須。
#)
#SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = '810525064687-m923adfs7g2gk3u4gtld8ab1j1h8r7ae.apps.googleusercontent.com'  # クライアントID
#SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = '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' # クライアント シークレット
# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'ja'

TIME_ZONE = 'Asia/Tokyo'

USE_I18N = True
DATETIME_FORMAT = '%yyyy/%mm/%dd'
USE_L10N = False

USE_TZ = False

from django.conf.global_settings import DATETIME_INPUT_FORMATS
DATETIME_INPUT_FORMATS += ('%yyyy/%mm/%dd',)
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
""" --------------追記----------------"""
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#heroku用設定--------------------------------------
#https://qiita.com/t-iguchi/items/718674a18fd151dfee49
import dj_database_url
DATABASES['default'] = dj_database_url.config()

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

ALLOWED_HOSTS = ['*']

STATIC_ROOT = 'staticfiles'

DEBUG = False

try:
    from .local_settings import *
except ImportError:
    pass

from whitenoise.django import DjangoWhiteNoise
application = DjangoWhiteNoise(application)
