# Generated by Django 4.0.5 on 2022-07-21 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappC', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order3',
            options={'verbose_name': '注文情報(Amazon)', 'verbose_name_plural': '注文情報(Amazon)'},
        ),
        migrations.AlterModelOptions(
            name='orderitemdetail3',
            options={'verbose_name': '決済情報(Amazonﾍﾟｲﾒﾝﾄ)', 'verbose_name_plural': '決済情報(Amazonﾍﾟｲﾒﾝﾄ)'},
        ),
        migrations.RemoveField(
            model_name='order3',
            name='correction_amount',
        ),
        migrations.RemoveField(
            model_name='order3',
            name='delivery_fee',
        ),
        migrations.RemoveField(
            model_name='order3',
            name='group',
        ),
        migrations.RemoveField(
            model_name='order3',
            name='method',
        ),
        migrations.RemoveField(
            model_name='order3',
            name='point',
        ),
        migrations.RemoveField(
            model_name='order3',
            name='slip',
        ),
        migrations.RemoveField(
            model_name='orderitemdetail3',
            name='name',
        ),
        migrations.RemoveField(
            model_name='orderitemdetail3',
            name='payment_code',
        ),
        migrations.AddField(
            model_name='order3',
            name='coupon_code',
            field=models.CharField(default=1, max_length=30, verbose_name='クーポンコード'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order3',
            name='postage_tax',
            field=models.IntegerField(blank=True, null=True, verbose_name='消費税(送料)'),
        ),
        migrations.AlterField(
            model_name='order3',
            name='postage',
            field=models.IntegerField(blank=True, null=True, verbose_name='送料'),
        ),
    ]
