# Generated by Django 4.0.5 on 2022-07-26 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myappC', '0005_alter_order3_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order3',
            old_name='code',
            new_name='order_code',
        ),
    ]
