# Generated by Django 4.0.5 on 2022-07-26 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myappC', '0006_rename_code_order3_order_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order3',
            old_name='order_code',
            new_name='code',
        ),
    ]
